### ISSUE TITLE
Q&A: Where is this related to blood type test?

### ISSUE THREAD

**Issue by jeffprestes** [docknetwork/crypto-wasm-ts#14]
I was reading this test but I could not see where the "blood" comes in this test?
https://github.com/docknetwork/crypto-wasm-ts/blob/master/tests/composite-proofs/msg-js-obj/r1cs/mimc-hash.spec.ts

**Comment by mike-parkhill** [comment]
I think you caught a case of copy and pasting and forgetting to update the test description

**Comment by jeffprestes** [comment]
hahaha, ... ok ... so, should I open an issue to ask to @lovesh to finish the test case?
I am writing in here because I believe the use case is a good one.

**Comment by lovesh** [comment]
@jeffprestes Thanks for pointing this, fixed [here](https://github.com/docknetwork/crypto-wasm-ts/commit/235b7f0c9b866e6c780d758b15c136f335acc445). 

> I believe the use case is a good one

You mean MiMC one or blood group?

**Comment by jeffprestes** [comment]
Blood group.

**Comment by lovesh** [comment]
[The blood group test](https://github.com/docknetwork/crypto-wasm-ts/blob/master/tests/composite-proofs/msg-js-obj/r1cs/blood-group.spec.ts).
